#!/usr/bin/env python3
"""Generate the parameter and analysis annex from the model.

Run: python3 tools/gen_tables.py > docs/annex-a-parameters.md

Every table in the blueprint that contains a number is produced here, so the
prose can never drift away from the code that implements it.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from model.rcu.classes import REGISTER, TIER_A, TIER_B, Tier  # noqa: E402
from model.rcu.hoarding import simulate  # noqa: E402
from model.rcu.units import (  # noqa: E402
    PHYSICAL_HAIRCUT,
    UNIT_DEFINITION,
    UnitBasis,
    numeraire_saving,
    ranked_numeraires,
)
from model.rcu.stress import (  # noqa: E402
    LIQUIDITY_DEPTH,
    harvest_cycle,
    redemption_run,
    survivable_crash,
)
from model.rcu.valuation import Note  # noqa: E402

W = sys.stdout.write


def pct(x: float, dp: int = 1) -> str:
    return f"{x * 100:.{dp}f}%"


def rate_str(c) -> str:
    if not c.decays:
        return "0"
    unit = "mo" if c.decay_period.value == "month" else "yr"
    return f"{c.decay_rate * 100:g}%/{unit}"


def validity(c) -> str:
    if c.max_validity_months is None:
        return "none"
    return f"{c.max_validity_months} mo"


def header() -> None:
    W("# Annex A — Class parameters and stress-test results\n\n")
    W("*Generated by `tools/gen_tables.py` from `model/rcu/`. Do not edit by hand.*\n\n")
    W(
        "All figures below are computed from the parameter register in "
        "`model/rcu/classes.py`. Where a figure is a judgement call rather than "
        "a measurement, it is flagged as such — a pilot's first job is to "
        "replace these with observed local data.\n\n"
    )


def table_classes() -> None:
    W("## A.1 The twenty classes\n\n")
    for tier, rows, title in (
        (Tier.A, TIER_A, "Tier A — demurrage-bearing"),
        (Tier.B, TIER_B, "Tier B — stable"),
    ):
        W(f"### {title}\n\n")
        W("| # | Code | Class | Colour | Grace | Decay | Max validity | Haircut | Unit |\n")
        W("|---|------|-------|--------|-------|-------|--------------|---------|------|\n")
        for c in rows:
            W(
                f"| {c.number} | `{c.code}` | {c.name} | {c.colour} `{c.hex_colour}` | "
                f"{c.grace_months} mo | {rate_str(c)} | {validity(c)} | "
                f"{pct(c.haircut, 0)} | {c.unit} |\n"
            )
        W("\n")


def table_carry() -> None:
    W("## A.2 Does demurrage pay for storage?\n\n")
    W(
        "A class whose annualised demurrage is below its physical cost of carry "
        "is structurally loss-making: the shortfall must be met by a custody fee, "
        "by the depositor, or by the stabilisation fund. There is no fourth option.\n\n"
    )
    W("| Code | Class | Demurrage/yr | Storage cost/yr | Gap | Funding required |\n")
    W("|------|-------|--------------|-----------------|-----|------------------|\n")
    for c in REGISTER:
        gap = c.storage_cost_pa - c.annualised_decay
        verdict = "covered" if c.carry_covered else f"**custody fee {pct(gap, 2)}**"
        W(
            f"| `{c.code}` | {c.name} | {pct(c.annualised_decay, 2)} | "
            f"{pct(c.storage_cost_pa, 2)} | {pct(gap, 2) if gap > 0 else '—'} | {verdict} |\n"
        )
    covered = sum(1 for c in REGISTER if c.carry_covered)
    W(
        f"\n**{len(REGISTER) - covered} of {len(REGISTER)} classes require an explicit "
        "custody fee.** Every one of them is in Tier B. This is the central "
        "economic consequence of a stable tier: stability is not free, and "
        "somebody has to pay the warehouse.\n\n"
    )


def table_lifetime() -> None:
    W("## A.3 Lifetime value loss on Tier A notes\n\n")
    W(
        "What a holder loses by sitting on a note until it expires. This is the "
        "circulation incentive, quantified.\n\n"
    )
    W("| Code | Class | Grace | Max validity | Loss if held to expiry |\n")
    W("|------|-------|-------|--------------|------------------------|\n")
    for c in TIER_A:
        W(
            f"| `{c.code}` | {c.name} | {c.grace_months} mo | "
            f"{c.max_validity_months} mo | {pct(c.lifetime_decay)} |\n"
        )
    W("\n")


def table_crash() -> None:
    W("## A.4 Price-crash resilience\n\n")
    W(
        "The largest one-shot fall in the local price of the collateral that a "
        "class can absorb while remaining fully collateralised, solved by "
        "bisection on `model/rcu/stress.py::price_crash`. Compare each figure "
        "against the class's own annual price volatility: **a class whose "
        "survivable crash is smaller than its one-sigma annual move is "
        "under-haircut.**\n\n"
    )
    W("| Code | Class | Haircut | Survivable fall | Annual volatility (1σ) | Verdict |\n")
    W("|------|-------|---------|-----------------|------------------------|---------|\n")
    weak = []
    for c in REGISTER:
        s = survivable_crash(c.code)
        ok = s >= c.price_volatility_pa
        if not ok:
            weak.append((c, s))
        W(
            f"| `{c.code}` | {c.name} | {pct(c.haircut, 0)} | {pct(s)} | "
            f"{pct(c.price_volatility_pa, 0)} | {'ok' if ok else '**under-haircut**'} |\n"
        )
    W("\n")
    if weak:
        W("**Under-haircut classes requiring parameter revision before issuance:**\n\n")
        for c, s in weak:
            need = 1 - (1 - c.price_volatility_pa) * (1 - c.haircut) / (1 - s) \
                if s < 1 else c.haircut
            W(
                f"- `{c.code}` {c.name}: survives {pct(s)} against {pct(c.price_volatility_pa, 0)} "
                f"volatility. Raise the haircut or cap the class.\n"
            )
        W("\n")


def table_liquidity() -> None:
    W("## A.5 Redemption capacity\n\n")
    W(
        "The share of outstanding notes that can be redeemed for physical goods "
        "within 30 days before the redemption gate must be invoked. Assumes a "
        "10% cash buffer plus the class's 30-day saleable depth.\n\n"
    )
    W("| Code | Class | Market depth | 30-day saleable | Max run honourable | 30% run |\n")
    W("|------|-------|--------------|-----------------|--------------------|---------|\n")
    for c in REGISTER:
        depth = LIQUIDITY_DEPTH.get(c.liquidity, 0.10)
        f = 0.0
        while f < 1.0 and not redemption_run(c.code, presented_fraction=f + 0.01).gate_triggered:
            f += 0.01
        rr = redemption_run(c.code)
        W(
            f"| `{c.code}` | {c.name} | {c.liquidity} | {pct(depth, 0)} | "
            f"{pct(f, 0)} | {'survives' if not rr.gate_triggered else '**gate**'} |\n"
        )
    W(
        "\nClasses that cannot honour a 30% run are not thereby invalid — cash "
        "cannot honour a 30% run either. They do mean the redemption gate is a "
        "*normal operating instrument*, not an emergency measure, and must be "
        "disclosed on the note itself.\n\n"
    )


def table_schedule() -> None:
    W("## A.6 Worked decay schedules\n\n")
    W("Value of a 1,000 RCU note by month of age, for representative classes.\n\n")
    picks = ["GR", "FP", "LV", "WD", "SC", "FE"]
    notes = {
        code: Note(
            serial=f"{code}-DEMO",
            class_code=code,
            face_cents=100_000,
            issued=date(2027, 1, 1),
            issuer_id="DEMO",
            warehouse_id="DEMO",
        )
        for code in picks
    }
    months = [0, 1, 3, 6, 9, 12, 18, 24, 36, 48]
    W("| Age (months) | " + " | ".join(f"`{c}`" for c in picks) + " |\n")
    W("|---" * (len(picks) + 1) + "|\n")
    sched = {c: dict(notes[c].schedule(60)) for c in picks}
    for m in months:
        cells = []
        for c in picks:
            v = sched[c].get(m, 0)
            cells.append("expired" if v == 0 and m > 0 else f"{v / 100:,.2f}")
        W(f"| {m} | " + " | ".join(cells) + " |\n")
    W("\n")


def table_harvest() -> None:
    W("## A.7 Seasonal money supply — single-crop cooperative\n\n")
    W(
        "A grain cooperative issuing once a year at harvest, 100,000 RCU of "
        "assessed deposit each cycle, 30% haircut. Shows the sawtooth money "
        "supply that a single-crop region will experience.\n\n"
    )
    r = harvest_cycle("GR", horizon=48)
    W("| Month | Outstanding (RCU) | Collateral (RCU) | Coverage |\n")
    W("|-------|-------------------|------------------|----------|\n")
    for m in range(0, 48, 3):
        out = r.outstanding[m] / 100
        col = r.collateral[m] / 100
        ratio = r.ratio[m]
        rs = "n/a" if ratio == float("inf") else f"{ratio:.2f}×"
        W(f"| {m} | {out:,.0f} | {col:,.0f} | {rs} |\n")
    finite = [x for x in r.ratio if x != float("inf")]
    W(
        f"\nMinimum coverage over 48 months: **{min(finite):.2f}×**. "
        f"Coverage never falls below 1.0, so the design is solvent under a "
        "pure harvest cycle with no price shock. The money supply, however, "
        f"swings from 0 to {max(r.outstanding) / 100:,.0f} RCU and back within "
        "each year — a single-crop cooperative cannot supply a stable medium of "
        "exchange on its own. **Classes must be pooled across differently-timed "
        "harvests, or the region will have a liquidity drought every lean season.**\n\n"
    )


def table_bundles() -> None:
    W("## A.8 Bundle pricing versus demurrage arbitrage\n\n")
    W(
        "Two agents with identical holdings and identical payment demands over "
        "24 months. The sophisticated agent chooses which notes to part with "
        "wherever the rules allow. The burden ratio is naive loss divided by "
        "sophisticated loss: **1.00 means demurrage is borne equally**, and "
        "higher values mean the unsophisticated are carrying it.\n\n"
    )
    W("| Payment rule | Sophisticated loss | Naive loss | Burden ratio |\n")
    W("|---|---|---|---|\n")
    for strict, label in ((False, "Free substitution"), (True, "Strict bundles")):
        r = simulate(strict=strict, months=24, tier_a_demand_share=0.5)
        W(
            f"| {label} | {r.sophisticated_loss:.1f} | {r.naive_loss:.1f} | "
            f"**{r.loss_ratio:.2f}** |\n"
        )
    W("\n### Sensitivity to the Tier A share of quoted bundles\n\n")
    W("| Tier A share of demand | Strict bundles | Free substitution |\n")
    W("|---|---|---|\n")
    for pct in (30, 40, 50, 60, 70):
        s = simulate(strict=True, months=24, tier_a_demand_share=pct / 100)
        f = simulate(strict=False, months=24, tier_a_demand_share=pct / 100)
        fr = "n/a" if f.loss_ratio == float("inf") else f"{f.loss_ratio:.2f}"
        W(f"| {pct}% | {s.loss_ratio:.2f} | {fr} |\n")
    W(
        "\nStrict bundle pricing equalises the burden across every demand mix "
        "tested. See section 12.3 for the partial-adoption result, which is "
        "non-monotonic and is the binding operational constraint.\n\n"
    )


def table_weight() -> None:
    W("## A.9 Weight denomination: haircuts and units\n\n")
    W(
        "Under weight denomination a note claims a physical quantity, so the "
        "haircut no longer has to absorb price risk -- only weighing error, "
        "moisture and shrinkage. See section 13.\n\n"
    )
    W("| Code | Class | Unit basis | Reference unit | Price haircut | Physical haircut |\n")
    W("|------|-------|-----------|----------------|---------------|------------------|\n")
    mon = []
    for c in REGISTER:
        basis, ref = UNIT_DEFINITION[c.code]
        ph = PHYSICAL_HAIRCUT.get(c.code)
        if ph is None:
            phs = "**not monetisable**"
        else:
            phs = pct(float(ph), 0)
            mon.append((float(c.haircut), float(ph)))
        W(
            f"| `{c.code}` | {c.name} | {basis} | {ref} | {pct(c.haircut, 0)} | {phs} |\n"
        )
    old = sum(a for a, _ in mon) / len(mon)
    new = sum(b for _, b in mon) / len(mon)
    W(
        f"\n**Average across monetisable classes: {pct(old)} -> {pct(new)}**, "
        f"freeing roughly {(old - new) * 100:.0f} percentage points of collateral "
        "back to depositors. A producer receives about 92 kg-units per 100 kg of "
        "Grade A maize, instead of 70 units of contested value.\n\n"
    )

    W("### Cost: exchange rates without a common unit\n\n")
    W("| Goods in market | Bilateral rates | With a numeraire | Ratio |\n")
    W("|---|---|---|---|\n")
    for n in (4, 10, 20, 50):
        w, m, r = numeraire_saving(n)
        W(f"| {n} | {w} | {m} | {r:.0f}x |\n")
    W("\n### Which class is likely to become the reference good\n\n")
    W("| Rank | Class | Score |\n|---|---|---|\n")
    for i, (c, s) in enumerate(ranked_numeraires()[:5], 1):
        W(f"| {i} | {c.name} (`{c.code}`) | {s} |\n")
    W(
        "\nIron is the realistic winner for a rural market: stable, universally "
        "wanted, cheap to store, divisible, and verifiable with a scale and a "
        "magnet. Precious metals scores higher but is too valuable per gram for "
        "daily use. The system should not mandate a numeraire -- that would "
        "recreate the price-setting authority weight denomination abolishes -- "
        "but should ensure the likely winner is exceptionally well run.\n\n"
    )


def main() -> None:
    header()
    table_classes()
    table_carry()
    table_lifetime()
    table_crash()
    table_liquidity()
    table_schedule()
    table_harvest()
    table_bundles()
    table_weight()


if __name__ == "__main__":
    main()
